### ISSUE TITLE
where is "flexsc_register()"? 

### ISSUE THREAD

**Issue by rupc** [spinlock/flexsc#1]
Hi. I read flexsc(OSDI 10) and found your implementation.

The paper mentioned two exception based system calls: flexsc_wait(), flexsc_register().

But when I typed "grep 'flexsc_register' * -r" in your project, It didn't print anything. 

And It seems that even flexsc_wait() function is not system call which is in eglibc.

Could you explain why you didn't implement flexsc_register() and why flexsc_wait() is not in linux-2.6?

Thanks in advance!

**Comment by spinlock** [comment]
Hi, @rupc 
I implemented a `fiber` framework in eglibc. You can find those files by `find -name flexsc_*`.
