### ISSUE TITLE
How do the shared memory implemented in your code?

### ISSUE THREAD

**Issue by Rexliang** [spinlock/flexsc#2]
Hi,I read your source code,but I don't know how do you implement the shared memory(flexsc_syspage?) between kernel and user.Can you help me?

**Comment by spinlock** [comment]
搜 `sys_flexsc_init` `flexsc_mmap` 在 kernel。其实就是通过 mmap 预先分配一下 stack。并把 virtual address 记下来。

**Comment by spinlock** [comment]
syscall 的时候，所有参数都在 stack 上，并且把所有 syscall 组织成 linked list。其实就够了。

都是小 trick...

**Comment by Rexliang** [comment]
哇，谢谢你。。。不过我对内核了解还很粗浅，你说的我不是很懂，想问几个原理上的问题：
1.mmap可以指定分配内核空间的物理内存吗？就比如32位系统的低1GB页框？
2.flexsc_init中的mmap是预先建立了一个内核栈到用户地址空间的映射吗？当系统调用的时候直接从内核栈取参数？这样理解对吗？

**Comment by spinlock** [comment]
和 stack 其实没有关系。。

1. fiber_init 的时候，内核分配了一块连续的物理地址并把它 mmap 到用户地址空间。
2. kernel 知道这个 virtual <-> physical 地址之间的映射关系，并且能够通过内核地址空间直接访问这块内存。
3. 传参数的时候，flexsc 负责把 syscall 参数、组织关系维护在这段内存上（通过 virtual address 写数据）。
4. 但是进入 kernel 之后，kernel 可以直接内核地址空间直接访问这块内存，拿到参数。。

建议你看一下清华的 OS 课程了解一下。这个项目对 OS 基础知识的要求不是一般的难。。

**Comment by spinlock** [comment]
另外，这个项目其实很坑。

OSDI 10' 的文章在 12' 已经过时了：Intel 指令集的优化，使得这篇文章所针对的问题已经基本上解决了，所以文章里面的性能曲线基本上在 12年就已经重复不出来了。

建议不要在实现上浪费太多时间。当然文章的思想还是比较有趣的。flexsc + message passing.

**Comment by Rexliang** [comment]
这下子看明白了，谢谢~~另外也谢谢你指点迷津，相关的文章我看的少，你说的12年的文章还没看过。
系统这方面自己看真是大坑，我去瞅瞅ucore去、

**Comment by spinlock** [comment]
😳

不是 12年的文章。是至少在 12年的时候，主流 Intel 芯片已经没有文章里面提到的存在的问题了。。剩下的都是实现技巧了。而且 eglibc 的代码不是一般的糟糕。（非常难读、改、编译）

**Comment by Rexliang** [comment]
才看见邮件。。
不是很明白你说的指令集优化具体指的是什么，手册我没有怎么看过，以前的东西知道的也少，请问是指的PCID还是什么吗？
我现在还处在刚入门的阶段，远不到看出代码好坏的水平，不过之前学linux的时候一直奇怪操作系统书上的多对一线程模型在哪儿，看了你的代码才知道nptl，也算收获颇丰：-）

**Comment by spinlock** [comment]
@Rexliang FlexSC 之所以在 paper 里面显示效果出众，是因为在早期 Intel 芯片上，无论是 INT 指令还是 SYSENTER/SYSEXIT 效率都非常的低，所以对 Syscall 进行 batch 能显著降低 context switch 的开销。

但是从 Xeon 开始，印象中差不多是这代开始，SYSENTER/SYSEXIT 这对指令的开销应该是有数量级的下降，所以直接结果就是，为了对 Syscall 进行 batch 而引入的代码的开销和 context switch 的开销差不多了。所以 FlexSC 的优势就仅剩下：syscall 进行 pipeline 处理减少内核锁竞争和降低 cache miss。虽然这种 micro benchmark 很多，但是意义真的很难说有多大。

**Comment by Rexliang** [comment]
原来是这样啊，我看这篇文章的时候一直以为batch和降低cache miss是主要原因，没考虑过sysenter/syscall 指令的效率的影响。还是要学习一个。B-)

**Comment by spinlock** [comment]
@Rexliang 是一个原因。所以取决于测试集。就是说在现有的芯片上（12年以后），FlexSC 基本上只在 Scheduler Intensive 的测试集上有效果，比如解决锁竞争问题；但是在 12年之前，就是写 paper 的时候，效果夸张的好，哪怕是 IO Intensive 的。所以这个 Paper 听坑的其实。

**Comment by Rexliang** [comment]
不过都比我牛啦~能学到思想和知识就好。这个现在已经不在看了，之前是想练练手熟悉一下内核，现在老板要我搞内存系统，边搞边学吧。
